name:
    platybrowser
channels:
    - cpape
    - conda-forge
dependencies:
    # - affogato
    - scikit-image
    - luigi
    - nifty
    - vigra
    - h5py
    - z5py
    - cluster_tools
    - paintera_tools
    - pandas
