# Specify the names of the datasets
dataset_names:
  - '2'
  - '4'

# Specify how the data needs to be sliced before feeding to the network.
# We use a 3D sliding window over the dataset to extract patches, which
# are then fed to the network as batches.
slicing_config:
  # Sliding window size
  window_size:
    [48, 320, 320]
  # Sliding window stride
  stride:
    [4, 32, 32]
  data_slice:
    "16:-16,32:-32,32:-32"
    
# Specify paths to volumes
volume_config:
  # Raw data
  raw:
    path:
      '2': '/g/kreshuk/data/arendt/platyneris_v1/training_data/nuclei/train_data_nuclei_02.h5'
      '4': '/g/kreshuk/data/arendt/platyneris_v1/training_data/nuclei/train_data_nuclei_04.h5'
    path_in_file:
      '2': 'volumes/raw'
      '4': 'volumes/raw'
    dtype: float32
    sigma: 0.05
  # Segmentation
  segmentation:
    path:
      '2': '/g/kreshuk/data/arendt/platyneris_v1/training_data/nuclei/train_data_nuclei_02.h5'
      '4': '/g/kreshuk/data/arendt/platyneris_v1/training_data/nuclei/train_data_nuclei_04.h5'
    path_in_file:
      '2': 'volumes/labels/nucleus_binary_labels'
      '4': 'volumes/labels/nucleus_binary_labels'
    dtype: float32
    label_volume: False
  rejection_value: -1


# Configuration for the master dataset.
master_config:
  # We might need order 0 interpolation if we have segmentation in there somewhere.
  elastic_transform:
    alpha: 2000.
    sigma: 50.
    order: 0


# Specify configuration for the loader
loader_config:
  # Number of processes to use for loading data. Set to (say) 10 if you wish to
  # use 10 CPU cores, or to 0 if you wish to use the same process for training and
  # data-loading (generally not recommended).
  batch_size: 1
  num_workers: 1
  drop_last: True
  pin_memory: False
  shuffle: True
